apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: awesome-app
    # Add this
    version: v0.0.1
  # Add version to deployment name
  name: awesome-app-v0.0.1
spec:
  selector:
    matchLabels:
      app: awesome-app
  replicas: 7
  template:
    metadata:
      labels:
        app: awesome-app
    spec:
      containers:
      - image: 'awesome-app:v0.0.1'
        name: awesome-app
        ports:
        - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: awesome-app
    # Add this
    version: v0.0.1
  name: awesome-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: awesome-app
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: awesome-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: awesome-app
  minReplicas: 7
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
