# Run with:
# NAMESPACE=canary-test \
#   VERSION=v0.0.2 \
#   INTERVAL=60 \
#   TRAFFIC_INCEMENT=20 \
#   DEPLOYMENT=awesome-app \
#   SERVICE=awesome-app \
#   HPA=awesome-app \                # optional var
#   HEALTHCHECK=/path/to/my/script \ # optional var
#   ON_FAILURE=/path/to/script \     # optional var
#   KUBE_CONTEXT=context \           # optional var
#   canary.sh

apiVersion: v1
kind: Service
metadata:
  namespace: canary-test
  name: awesome-app
  labels:
    # Version label is required
    version: v1.0.0
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: awesome-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: canary-test
  # Version appended to name is required
  name: awesome-app-v1.0.0
spec:
  replicas: 7
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # App label is required
        app: awesome-app
    spec:
      containers:
      - image: 'awesome-app:v1.0.0'
        name: awesome-app
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: 'production'
      restartPolicy: Always
---
# If using an HPA, make sure you provide the name as a variable,
# otherwise your HPA will continue targeting the previous deployment.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: canary-test
  name: awesome-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # Name target with version appended is required
    name: awesome-app-v1.0.0
  minReplicas: 7
  maxReplicas: 14
  targetCPUUtilizationPercentage: 70
